// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb_B4AaKjeMMGYELEd4wEkK8ohPOZkb5g',
    appId: '1:1088547227097:android:2cb933400dedd9a5a605c8',
    messagingSenderId: '1088547227097',
    projectId: 'mcitest-4d24a',
    storageBucket: 'mcitest-4d24a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNSVEupbMWa3qquMhllHirsFS-kKkBG04',
    appId: '1:1088547227097:ios:250f174b58c4b010a605c8',
    messagingSenderId: '1088547227097',
    projectId: 'mcitest-4d24a',
    storageBucket: 'mcitest-4d24a.firebasestorage.app',
    iosBundleId: 'com.example.mciTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNSVEupbMWa3qquMhllHirsFS-kKkBG04',
    appId: '1:1088547227097:ios:250f174b58c4b010a605c8',
    messagingSenderId: '1088547227097',
    projectId: 'mcitest-4d24a',
    storageBucket: 'mcitest-4d24a.firebasestorage.app',
    iosBundleId: 'com.example.mciTest',
  );
}
